//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng_Part.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModulePart
    {
        public int PartID { get; set; }
        public string PartName { get; set; }
        public string PartDesc { get; set; }
        public Nullable<bool> PartMetal { get; set; }
        public int PartDimension { get; set; }
        public string PartImage { get; set; }
        public Nullable<System.DateTime> PartCDate { get; set; }
        public Nullable<System.DateTime> PartMDate { get; set; }
    }
}
